apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-test
  namespace: tekton-pipelines
spec:
  description: Run npm tests for Node.js application
  params:
    - name: ARGS
      description: The npm arguments to run
      type: array
      default: ["test"]
    - name: IMAGE
      description: The node image to use
      type: string
      default: "node:18-alpine"
  workspaces:
    - name: source
      description: The workspace containing the source code
  steps:
    - name: npm-install
      image: $(params.IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Installing dependencies..."
        npm ci
    - name: npm-lint
      image: $(params.IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Running linter..."
        npm run lint || echo "Linting completed with warnings"
    - name: npm-test
      image: $(params.IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Running tests..."
        npm run test
        echo "Tests completed successfully!"