apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-webhook-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-pipeline-sa
  triggers:
    - name: github-push-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.ref == 'refs/heads/main'"
      bindings:
        - ref: github-push-binding
      template:
        ref: tekton-demo-trigger-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.head_commit.id)
    - name: git-branch
      value: $(body.ref)
    - name: commit-message
      value: $(body.head_commit.message)
    - name: commit-author
      value: $(body.head_commit.author.name)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tekton-demo-trigger-template
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
      description: The git repository URL
    - name: git-revision
      description: The git revision
      default: main
    - name: git-branch
      description: The git branch
      default: refs/heads/main
    - name: commit-message
      description: The commit message
      default: ""
    - name: commit-author
      description: The commit author
      default: ""
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: tekton-demo-pipeline-run-
        namespace: tekton-pipelines
        labels:
          app: tekton-demo
          pipeline: tekton-demo-pipeline
          trigger-type: webhook
      spec:
        serviceAccountName: tekton-pipeline-sa
        pipelineRef:
          name: tekton-demo-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image-registry
            value: "docker.io"
          - name: image-namespace
            value: "your-dockerhub-username"  # Replace with actual username
          - name: image-name
            value: "tekton-demo-app"
          - name: image-tag
            value: "$(tt.params.git-revision)"
          - name: deploy-namespace
            value: "default"
          - name: app-name
            value: "tekton-demo-app"
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: docker-credentials
            secret:
              secretName: docker-credentials
        timeouts:
          pipeline: "1h0m0s"
---
# Service to expose the EventListener
apiVersion: v1
kind: Service
metadata:
  name: el-github-webhook-listener
  namespace: tekton-pipelines
spec:
  selector:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: github-webhook-listener
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP